apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pod-affinity-anti-pods
  labels:
    purpose: learning
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      type: create
  template:
    metadata:
      name: httpd
      labels:
        devops: '18'
        company: talent
        type: create
    spec:
      containers:
      - name: httpd
        image: nginx
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: type
                operator: In
                values:
                - cicd
            topologyKey: topology.kubernetes.io/zone

