apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test-no-replicas
  labels:
    purpose: learning
  namespace: preprod
spec:
  selector:
    matchLabels:
      type: create
  template:
    metadata:
      name: httpd
      labels:
        devops: '18'
        company: talent
        type: create
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        ports:
        - containerPort: 80
